"""Primeira migração

Revision ID: 1193eb387e03
Revises: 
Create Date: 2026-01-14 10:26:25.039086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1193eb387e03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('detalhes', sa.DateTime(), nullable=False),
    sa.Column('remetente_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destinatario_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('reacts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('reacts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['postagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    op.drop_table('postagens')
    op.drop_table('mensagens')
    op.drop_table('enderecos')
    op.drop_table('users')
    # ### end Alembic commands ###
