"""Data e Conteudo  adicionados a comentario

Revision ID: 7acc24190581
Revises: ce3aaa900359
Create Date: 2026-02-18 12:28:04.074396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acc24190581'
down_revision = 'ce3aaa900359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conteudo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('conteudo')

    # ### end Alembic commands ###
