"""Campo Imagem adicionado em Postagem

Revision ID: ce3aaa900359
Revises: 1193eb387e03
Create Date: 2026-02-09 18:34:02.136618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3aaa900359'
down_revision = '1193eb387e03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postagens', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
